{% set name = "pycolmap" %}
{% set version = "0.4.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/colmap/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: cead12638a9746143143ba29a5cb6131a34d6e9555ade9c9d1b79b8eacfbf9cf
    patches:
      - use-conda-pybind11.patch
      - fix-win-build.patch
      - fix-pybind11.patch
      - fix-cuda-link.patch

build:
  number: 3
  script: {{ PYTHON }} -m pip install . -vv
  string: cuda{{ cuda_compiler_version | replace('.', '') }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version not in (undefined, "None")]
  string: cpu_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version in (undefined, "None")]
  # weigh down cpu implementation and give cuda preference
  track_features:
    - pycolmap-cpu  # [cuda_compiler_version in (undefined, "None")]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ compiler('cuda') }}                 # [cuda_compiler_version not in (undefined, "None")]
    - cmake
    - make                                   # [unix]
    - ninja                                  # [win]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    # x11 stuff
    - {{ cdt('mesa-libgl-devel') }}          # [unix and not arm64]
    - {{ cdt('mesa-dri-drivers') }}          # [unix and not arm64]
    - {{ cdt('libselinux') }}                # [linux]
    - {{ cdt('libxcb') }}                    # [linux]
    - {{ cdt('libxdamage') }}                # [linux]
    - {{ cdt('libxfixes') }}                 # [linux]
    - {{ cdt('libxxf86vm') }}                # [linux]
    - {{ cdt('libxext') }}                   # [linux]
    - {{ cdt('libxau') }}                    # [linux]
    - {{ cdt('expat-devel') }}               # [linux]
    - sysroot_linux-64 2.17                  # [linux64]
    - llvm-openmp                            # [osx]
    - libgomp                                # [linux]
  host:
    - pip
    - python
    - pybind11
    - libboost-devel
    - colmap
    - libblas
    - libcblas
    - cgal-cpp
    - sqlite
    - flann
    - glog
    - gflags
    - flann
    - freeimage
    - metis
    - ceres-solver
    - glew
    - vlfeat                                 # [unix]
    - gmp                                    # [unix]
    - qt-main
    - mpir                                   # [win]
    - cuda-cudart-dev                        # [(cuda_compiler_version or "").startswith("12")]
  run:
    - python
    - flann
    - vlfeat
    - numpy
    - __cuda >={{ cuda_compiler_version }}   # [cuda_compiler_version not in (undefined, "None")]

test:
  imports:
    - pycolmap
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://colmap.github.io/
  license: BSD-3-Clause
  license_file:
    - LICENSE
  summary: pycolmap exposes to Python most COLMAP reconstruction objects, such as Cameras and Points3D, as well as estimators for absolute and relative poses.

extra:
  recipe-maintainers:
    - Tobias-Fischer
