azure:
  free_disk_space: true
bot:
  automerge: true
  abi_migration_branches:
  - 0.4.0
build_platform:
  linux_aarch64: linux_64
  osx_arm64: osx_64
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
test: native_and_emulated
